"""Add notifications table

Revision ID: 19d595807e03
Revises: 704cad2886b1
Create Date: 2026-07-22 13:59:25.254466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d595807e03'
down_revision = '704cad2886b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('previous_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('performed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['performed_by'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('old_status')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('escalation_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('escalation_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('complaint_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('old_status', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('performed_by')
        batch_op.drop_column('previous_status')
        batch_op.drop_column('action')

    op.drop_table('notifications')
    # ### end Alembic commands ###
